package pl.banking.enums;

import java.io.Serializable;

public enum Countries implements Serializable{
    AFGHANISTAN("AF", "Afghanistan"),
    ALBANIA("AL", "Albania"),
    ALGERIA("DZ", "Algeria"),
    AMERICAN_SAMOA("AS", "American Samoa"),
    ANDORRA("AD", "Andorra"),
    ANGOLA("AO", "Angola"),
    ANGUILLA("AI", "Anguilla"),
    ANTARCTICA("AQ", "Antarctica"),
    ANTIGUA_AND_BARBUDA("AG", "Antigua And Barbuda"),
    ARGENTINA("AR", "Argentina"),
    ARMENIA("AM", "Armenia"),
    ARUBA("AW", "Aruba"),
    AUSTRALIA("AU", "Australia"),
    AUSTRIA("AT", "Austria"),
    AZERBAIJAN("AZ", "Azerbaijan"),
    BAHAMAS("BS", "Bahamas"),
    BAHRAIN("BH", "Bahrain"),
    BANGLADESH("BD", "Bangladesh"),
    BARBADOS("BB", "Barbados"),
    BELARUS("BY", "Belarus"),
    BELGIUM("BE", "Belgium"),
    BELIZE("BZ", "Belize"),
    BENIN("BJ", "Benin"),
    BERMUDA("BM", "Bermuda"),
    BHUTAN("BT", "Bhutan"),
    BOLIVIA("BO", "Bolivia"),
    BOSNIA_AND_HERZEGOVINA("BA", "Bosnia And Herzegovina"),
    BOTSWANA("BW", "Botswana"),
    BOUVET_ISLAND("BV", "Bouvet Island"),
    BRAZIL("BR", "Brazil"),
    BRITISH_INDIAN_OCEAN_TERRITORY("IO", "British Indian Ocean Territory"),
    BRUNEI_DARUSSALAM("BN", "Brunei Darussalam"),
    BULGARIA("BG", "Bulgaria"),
    BURKINA_FASO("BF", "Burkina Faso"),
    BURUNDI("BI", "Burundi"),
    CAMBODIA("KH", "Cambodia"),
    CAMEROON("CM", "Cameroon"),
    CANADA("CA", "Canada"),
    CAPE_VERDE("CV", "Cape Verde"),
    CAYMAN_ISLANDS("KY", "Cayman Islands"),
    CENTRAL_AFRICAN_REPUBLIC("CF", "Central African Republic"),
    CHAD("TD", "Chad"),
    CHILE("CL", "Chile"),
    CHINA("CN", "China"),
    CHRISTMAS_ISLAND("CX", "Christmas Island"),
    COCOS_KEELING_ISLANDS("CC", "Cocos (keeling) Islands"),
    COLOMBIA("CO", "Colombia"),
    COMOROS("KM", "Comoros"),
    CONGO("CG", "Congo"),
    CONGO_THE_DEMOCRATIC_REPUBLIC_OF_THE("CD", "Congo, The Democratic Republic Of The"),
    COOK_ISLANDS("CK", "Cook Islands"),
    COSTA_RICA("CR", "Costa Rica"),
    COTE_DIVOIRE("CI", "Cote D'ivoire"),
    CROATIA("HR", "Croatia"),
    CUBA("CU", "Cuba"),
    CYPRUS("CY", "Cyprus"),
    CZECH_REPUBLIC("CZ", "Czech Republic"),
    DENMARK("DK", "Denmark"),
    DJIBOUTI("DJ", "Djibouti"),
    DOMINICA("DM", "Dominica"),
    DOMINICAN_REPUBLIC("DO", "Dominican Republic"),
    EAST_TIMOR("TP", "East Timor"),
    ECUADOR("EC", "Ecuador"),
    EGYPT("EG", "Egypt"),
    EL_SALVADOR("SV", "El Salvador"),
    EQUATORIAL_GUINEA("GQ", "Equatorial Guinea"),
    ERITREA("ER", "Eritrea"),
    ESTONIA("EE", "Estonia"),
    ETHIOPIA("ET", "Ethiopia"),
    FALKLAND_ISLANDS_MALVINAS("FK", "Falkland Islands (malvinas)"),
    FAROE_ISLANDS("FO", "Faroe Islands"),
    FIJI("FJ", "Fiji"),
    FINLAND("FI", "Finland"),
    FRANCE("FR", "France"),
    FRENCH_GUIANA("GF", "French Guiana"),
    FRENCH_POLYNESIA("PF", "French Polynesia"),
    FRENCH_SOUTHERN_TERRITORIES("TF", "French Southern Territories"),
    GABON("GA", "Gabon"),
    GAMBIA("GM", "Gambia"),
    GEORGIA("GE", "Georgia"),
    GERMANY("DE", "Germany"),
    GHANA("GH", "Ghana"),
    GIBRALTAR("GI", "Gibraltar"),
    GREECE("GR", "Greece"),
    GREENLAND("GL", "Greenland"),
    GRENADA("GD", "Grenada"),
    GUADELOUPE("GP", "Guadeloupe"),
    GUAM("GU", "Guam"),
    GUATEMALA("GT", "Guatemala"),
    GUINEA("GN", "Guinea"),
    GUINEA_BISSAU("GW", "Guinea-bissau"),
    GUYANA("GY", "Guyana"),
    HAITI("HT", "Haiti"),
    HEARD_ISLAND_AND_MCDONALD_ISLANDS("HM", "Heard Island And Mcdonald Islands"),
    HOLY_SEE("VA", "Holy See (vatican City State)"),
    HONDURAS("HN", "Honduras"),
    HONG_KONG("HK", "Hong Kong"),
    HUNGARY("HU", "Hungary"),
    ICELAND("IS", "Iceland"),
    INDIA("IN", "India"),
    INDONESIA("ID", "Indonesia"),
    IRAN_ISLAMIC_REPUBLIC_OF("IR", "Iran, Islamic Republic Of"),
    IRAQ("IQ", "Iraq"),
    IRELAND("IE", "Ireland"),
    ISRAEL("IL", "Israel"),
    ITALY("IT", "Italy"),
    JAMAICA("JM", "Jamaica"),
    JAPAN("JP", "Japan"),
    JORDAN("JO", "Jordan"),
    KAZAKSTAN("KZ", "Kazakstan"),
    KENYA("KE", "Kenya"),
    KIRIBATI("KI", "Kiribati"),
    KOREA_DEMOCRATIC_PEOPLES_REPUBLIC_OF("KP", "Korea, Democratic People's Republic Of"),
    KOREA_REPUBLIC_OF("KR", "Korea, Republic Of"),
    KOSOVO("KV", "Kosovo"),
    KUWAIT("KW", "Kuwait"),
    KYRGYZSTAN("KG", "Kyrgyzstan"),
    LAO_PEOPLES_DEMOCRATIC_REPUBLIC("LA", "Lao People's Democratic Republic"),
    LATVIA("LV", "Latvia"),
    LEBANON("LB", "Lebanon"),
    LESOTHO("LS", "Lesotho"),
    LIBERIA("LR", "Liberia"),
    LIBYAN_ARAB_JAMAHIRIYA("LY", "Libyan Arab Jamahiriya"),
    LIECHTENSTEIN("LI", "Liechtenstein"),
    LITHUANIA("LT", "Lithuania"),
    LUXEMBOURG("LU", "Luxembourg"),
    MACAU("MO", "Macau"),
    MACEDONIA_THE_FORMER_YUGOSLAV_REPUBLIC_OF("MK", "Macedonia, The Former Yugoslav Republic Of"),
    MADAGASCAR("MG", "Madagascar"),
    MALAWI("MW", "Malawi"),
    MALAYSIA("MY", "Malaysia"),
    MALDIVES("MV", "Maldives"),
    MALI("ML", "Mali"),
    MALTA("MT", "Malta"),
    MARSHALL_ISLANDS("MH", "Marshall Islands"),
    MARTINIQUE("MQ", "Martinique"),
    MAURITANIA("MR", "Mauritania"),
    MAURITIUS("MU", "Mauritius"),
    MAYOTTE("YT", "Mayotte"),
    MEXICO("MX", "Mexico"),
    MICRONESIA_FEDERATED_STATES_OF("FM", "Micronesia, Federated States Of"),
    MOLDOVA_REPUBLIC_OF("MD", "Moldova, Republic Of"),
    MONACO("MC", "Monaco"),
    MONGOLIA("MN", "Mongolia"),
    MONTSERRAT("MS", "Montserrat"),
    MONTENEGRO("ME", "Montenegro"),
    MOROCCO("MA", "Morocco"),
    MOZAMBIQUE("MZ", "Mozambique"),
    MYANMAR("MM", "Myanmar"),
    NAMIBIA("NA", "Namibia"),
    NAURU("NR", "Nauru"),
    NEPAL("NP", "Nepal"),
    NETHERLANDS("NL", "Netherlands"),
    NETHERLANDS_ANTILLES("AN", "Netherlands Antilles"),
    NEW_CALEDONIA("NC", "New Caledonia"),
    NEW_ZEALAND("NZ", "New Zealand"),
    NICARAGUA("NI", "Nicaragua"),
    NIGER("NE", "Niger"),
    NIGERIA("NG", "Nigeria"),
    NIUE("NU", "Niue"),
    NORFOLK_ISLAND("NF", "Norfolk Island"),
    NORTHERN_MARIANA_ISLANDS("MP", "Northern Mariana Islands"),
    NORWAY("NO", "Norway"),
    OMAN("OM", "Oman"),
    PAKISTAN("PK", "Pakistan"),
    PALAU("PW", "Palau"),
    PALESTINIAN_TERRITORY_OCCUPIED("PS", "Palestinian Territory, Occupied"),
    PANAMA("PA", "Panama"),
    PAPUA_NEW_GUINEA("PG", "Papua New Guinea"),
    PARAGUAY("PY", "Paraguay"),
    PERU("PE", "Peru"),
    PHILIPPINES("PH", "Philippines"),
    PITCAIRN("PN", "Pitcairn"),
    POLAND("PL", "Poland"),
    PORTUGAL("PT", "Portugal"),
    PUERTO_RICO("PR", "Puerto Rico"),
    QATAR("QA", "Qatar"),
    REUNION("RE", "Reunion"),
    ROMANIA("RO", "Romania"),
    RUSSIAN_FEDERATION("RU", "Russian Federation"),
    RWANDA("RW", "Rwanda"),
    SAINT_HELENA("SH", "Saint Helena"),
    SAINT_KITTS_AND_NEVIS("KN", "Saint Kitts And Nevis"),
    SAINT_LUCIA("LC", "Saint Lucia"),
    SAINT_PIERRE_AND_MIQUELON("PM", "Saint Pierre And Miquelon"),
    SAINT_VINCENT_AND_THE_GRENADINES("VC", "Saint Vincent And The Grenadines"),
    SAMOA("WS", "Samoa"),
    SAN_MARINO("SM", "San Marino"),
    SAO_TOME_AND_PRINCIPE("ST", "Sao Tome And Principe"),
    SAUDI_ARABIA("SA", "Saudi Arabia"),
    SENEGAL("SN", "Senegal"),
    SERBIA("RS", "Serbia"),
    SEYCHELLES("SC", "Seychelles"),
    SIERRA_LEONE("SL", "Sierra Leone"),
    SINGAPORE("SG", "Singapore"),
    SLOVAKIA("SK", "Slovakia"),
    SLOVENIA("SI", "Slovenia"),
    SOLOMON_ISLANDS("SB", "Solomon Islands"),
    SOMALIA("SO", "Somalia"),
    SOUTH_AFRICA("ZA", "South Africa"),
    SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS("GS", "South Georgia And The South Sandwich Islands"),
    SPAIN("ES", "Spain"),
    SRI_LANKA("LK", "Sri Lanka"),
    SUDAN("SD", "Sudan"),
    SURINAME("SR", "Suriname"),
    SVALBARD_AND_JAN_MAYEN("SJ", "Svalbard And Jan Mayen"),
    SWAZILAND("SZ", "Swaziland"),
    SWEDEN("SE", "Sweden"),
    SWITZERLAND("CH", "Switzerland"),
    SYRIAN_ARAB_REPUBLIC("SY", "Syrian Arab Republic"),
    TAIWAN_PROVINCE_OF_CHINA("TW", "Taiwan, Province Of China"),
    TAJIKISTAN("TJ", "Tajikistan"),
    TANZANIA_UNITED_REPUBLIC_OF("TZ", "Tanzania, United Republic Of"),
    THAILAND("TH", "Thailand"),
    TOGO("TG", "Togo"),
    TOKELAU("TK", "Tokelau"),
    TONGA("TO", "Tonga"),
    TRINIDAD_AND_TOBAGO("TT", "Trinidad And Tobago"),
    TUNISIA("TN", "Tunisia"),
    TURKEY("TR", "Turkey"),
    TURKMENISTAN("TM", "Turkmenistan"),
    TURKS_AND_CAICOS_ISLANDS("TC", "Turks And Caicos Islands"),
    TUVALU("TV", "Tuvalu"),
    UGANDA("UG", "Uganda"),
    UKRAINE("UA", "Ukraine"),
    UNITED_ARAB_EMIRATES("AE", "United Arab Emirates"),
    UNITED_KINGDOM("GB", "United Kingdom"),
    UNITED_STATES("US", "United States"),
    UNITED_STATES_MINOR_OUTLYING_ISLANDS("UM", "United States Minor Outlying Islands"),
    URUGUAY("UY", "Uruguay"),
    UZBEKISTAN("UZ", "Uzbekistan"),
    VANUATU("VU", "Vanuatu"),
    VENEZUELA("VE", "Venezuela"),
    VIET_NAM("VN", "Viet Nam"),
    VIRGIN_ISLANDS_BRITISH("VG", "Virgin Islands, British"),
    VIRGIN_ISLANDS_US("VI", "Virgin Islands, U.s."),
    WALLIS_AND_FUTUNA("WF", "Wallis And Futuna"),
    WESTERN_SAHARA("EH", "Western Sahara"),
    YEMEN("YE", "Yemen"),
    ZAMBIA("ZM", "Zambia"),
    ZIMBABWE("ZW", "Zimbabwe");

    private String countryCode;
    private String countryName;
    
    private Countries(String countryCode, String countryName){
        this.countryCode = countryCode;
        this.countryName = countryName;
    }
    
    public String getCountryCode(){
        return countryCode;
    }
    
    public String getCountryName(){
        return countryName;
    }
}
