package pl.banking.enums;

public enum Nationalities {
    AFGHAN("Afghan"),
    ALBANIAN("Albanian"),
    ALGERIAN("Algerian"),
    AMERICAN("American"),
    ANDORRAN("Andorran"),
    ANGOLAN("Angolan"),
    ANTIGUANS("Antiguans"),
    ARGENTINEAN("Argentinean"),
    ARMENIAN("Armenian"),
    AUSTRALIAN("Australian"),
    AUSTRIAN("Austrian"),
    AZERBAIJANI("Azerbaijani"),
    BAHAMIAN("Bahamian"),
    BAHRAINI("Bahraini"),
    BANGLADESHI("Bangladeshi"),
    BARBADIAN("Barbadian"),
    BARBUDANS("Barbudans"),
    BATSWANA("Batswana"),
    BELARUSIAN("Belarusian"),
    BELGIAN("Belgian"),
    BELIZEAN("Belizean"),
    BENINESE("Beninese"),
    BHUTANESE("Bhutanese"),
    BOLIVIAN("Bolivian"),
    BOSNIAN("Bosnian"),
    BRAZILIAN("Brazilian"),
    BRITISH("British"),
    BRUNEIAN("Bruneian"),
    BULGARIAN("Bulgarian"),
    BURKINABE("Burkinabe"),
    BURMESE("Burmese"),
    BURUNDIAN("Burundian"),
    CAMBODIAN("Cambodian"),
    CAMEROONIAN("Cameroonian"),
    CANADIAN("Canadian"),
    CAPE_VERDEAN("Cape Verdean"),
    CENTRAL_AFRICAN("Central African"),
    CHADIAN("Chadian"),
    CHILEAN("Chilean"),
    CHINESE("Chinese"),
    COLOMBIAN("Colombian"),
    COMORAN("Comoran"),
    CONGOLESE("Congolese"),
    COSTA_RICAN("Costa Rican"),
    CROATIAN("Croatian"),
    CUBAN("Cuban"),
    CYPRIOT("Cypriot"),
    CZECH("Czech"),
    DANISH("Danish"),
    DJIBOUTI("Djibouti"),
    DOMINICAN("Dominican"),
    DUTCH("Dutch"),
    DUTCHMAN("Dutchman"),
    DUTCHWOMAN("Dutchwoman"),
    EAST_TIMORESE("East Timorese"),
    ECUADOREAN("Ecuadorean"),
    EGYPTIAN("Egyptian"),
    EMIRIAN("Emirian"),
    EQUATORIAL_GUINEAN("Equatorial Guinean"),
    ERITREAN("Eritrean"),
    ESTONIAN("Estonian"),
    ETHIOPIAN("Ethiopian"),
    FIJIAN("Fijian"),
    FILIPINO("Filipino"),
    FINNISH("Finnish"),
    FRENCH("French"),
    GABONESE("Gabonese"),
    GAMBIAN("Gambian"),
    GEORGIAN("Georgian"),
    GERMAN("German"),
    GHANAIAN("Ghanaian"),
    GREEK("Greek"),
    GRENADIAN("Grenadian"),
    GUATEMALAN("Guatemalan"),
    GUINEA_BISSAUAN("Guinea-Bissauan"),
    GUINEAN("Guinean"),
    GUYANESE("Guyanese"),
    HAITIAN("Haitian"),
    HERZEGOVINIAN("Herzegovinian"),
    HONDURAN("Honduran"),
    HUNGARIAN("Hungarian"),
    I_KIRIBATI("I-Kiribati"),
    ICELANDER("Icelander"),
    INDIAN("Indian"),
    INDONESIAN("Indonesian"),
    IRANIAN("Iranian"),
    IRAQI("Iraqi"),
    IRISH("Irish"),
    ISRAELI("Israeli"),
    ITALIAN("Italian"),
    IVORIAN("Ivorian"),
    JAMAICAN("Jamaican"),
    JAPANESE("Japanese"),
    JORDANIAN("Jordanian"),
    KAZAKHSTANI("Kazakhstani"),
    KENYAN("Kenyan"),
    KITTIAN_AND_NEVISIAN("Kittian and Nevisian"),
    KUWAITI("Kuwaiti"),
    KYRGYZ("Kyrgyz"),
    LAOTIAN("Laotian"),
    LATVIAN("Latvian"),
    LEBANESE("Lebanese"),
    LIBERIAN("Liberian"),
    LIBYAN("Libyan"),
    LIECHTENSTEINER("Liechtensteiner"),
    LITHUANIAN("Lithuanian"),
    LUXEMBOURGER("Luxembourger"),
    MACEDONIAN("Macedonian"),
    MALAGASY("Malagasy"),
    MALAWIAN("Malawian"),
    MALAYSIAN("Malaysian"),
    MALDIVAN("Maldivan"),
    MALIAN("Malian"),
    MALTESE("Maltese"),
    MARSHALLESE("Marshallese"),
    MAURITANIAN("Mauritanian"),
    MAURITIAN("Mauritian"),
    MEXICAN("Mexican"),
    MICRONESIAN("Micronesian"),
    MOLDOVAN("Moldovan"),
    MONACAN("Monacan"),
    MONGOLIAN("Mongolian"),
    MOROCCAN("Moroccan"),
    MOSOTHO("Mosotho"),
    MOTSWANA("Motswana"),
    MOZAMBICAN("Mozambican"),
    NAMIBIAN("Namibian"),
    NAURUAN("Nauruan"),
    NEPALESE("Nepalese"),
    NETHERLANDER("Netherlander"),
    NEW_ZEALANDER("New Zealander"),
    NI_VANUATU("Ni-Vanuatu"),
    NICARAGUAN("Nicaraguan"),
    NIGERIAN("Nigerian"),
    NIGERIEN("Nigerien"),
    NORTH_KOREAN("North Korean"),
    NORTHERN_IRISH("Northern Irish"),
    NORWEGIAN("Norwegian"),
    OMANI("Omani"),
    PAKISTANI("Pakistani"),
    PALAUAN("Palauan"),
    PANAMANIAN("Panamanian"),
    PAPUA_NEW_GUINEAN("Papua New Guinean"),
    PARAGUAYAN("Paraguayan"),
    PERUVIAN("Peruvian"),
    POLISH("Polish"),
    PORTUGUESE("Portuguese"),
    QATARI("Qatari"),
    ROMANIAN("Romanian"),
    RUSSIAN("Russian"),
    RWANDAN("Rwandan"),
    SAINT_LUCIAN("Saint Lucian"),
    SALVADORAN("Salvadoran"),
    SAMOAN("Samoan"),
    SAN_MARINESE("San Marinese"),
    SAO_TOMEAN("Sao Tomean"),
    SAUDI("Saudi"),
    SCOTTISH("Scottish"),
    SENEGALESE("Senegalese"),
    SERBIAN("Serbian"),
    SEYCHELLOIS("Seychellois"),
    SIERRA_LEONEAN("Sierra Leonean"),
    SINGAPOREAN("Singaporean"),
    SLOVAKIAN("Slovakian"),
    SLOVENIAN("Slovenian"),
    SOLOMON_ISLANDER("Solomon Islander"),
    SOMALI("Somali"),
    SOUTH_AFRICAN("South African"),
    SOUTH_KOREAN("South Korean"),
    SPANISH("Spanish"),
    SRI_LANKAN("Sri Lankan"),
    SUDANESE("Sudanese"),
    SURINAMER("Surinamer"),
    SWAZI("Swazi"),
    SWEDISH("Swedish"),
    SWISS("Swiss"),
    SYRIAN("Syrian"),
    TAIWANESE("Taiwanese"),
    TAJIK("Tajik"),
    TANZANIAN("Tanzanian"),
    THAI("Thai"),
    TOGOLESE("Togolese"),
    TONGAN("Tongan"),
    TRINIDADIAN_OR_TOBAGONIAN("Trinidadian or Tobagonian"),
    TUNISIAN("Tunisian"),
    TURKISH("Turkish"),
    TUVALUAN("Tuvaluan"),
    UGANDAN("Ugandan"),
    UKRAINIAN("Ukrainian"),
    URUGUAYAN("Uruguayan"),
    UZBEKISTANI("Uzbekistani"),
    VENEZUELAN("Venezuelan"),
    VIETNAMESE("Vietnamese"),
    WELSH("Welsh"),
    YEMENITE("Yemenite"),
    ZAMBIAN("Zambian"),
    ZIMBABWEAN("Zimbabwean");
    
    private String nationalityName;
    
    private Nationalities(String nationalityName){
        this.nationalityName = nationalityName;
    }
    
    public String getNationalityName(){
        return nationalityName;
    }
}
